version: '3'
services:
  nextcloud:
    build: .
    ports:
      - "80:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_HOST=your-db-endpoint
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your-password
    restart: always

volumes:
  nextcloud_data:

