name: Build and Deploy to 2 EC2 Instances

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push to ECR
      run: |
        docker build -t nextcloud-repo docker/
        docker tag nextcloud-repo:latest 585685714619.dkr.ecr.ap-northeast-2.amazonaws.com/nextcloud-repo:latest
        docker push 585685714619.dkr.ecr.ap-northeast-2.amazonaws.com/nextcloud-repo:latest

    # ✅ EC2 인스턴스 1에 배포
    - name: Deploy to EC2 Instance 1 (3.35.136.9)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 3.35.136.9
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 585685714619.dkr.ecr.ap-northeast-2.amazonaws.com
          docker pull 585685714619.dkr.ecr.ap-northeast-2.amazonaws.com/nextcloud-repo:latest
          docker stop nextcloud-app || true
          docker rm nextcloud-app || true
          docker run -d \
            --name nextcloud-app \
            -p 80:80 \
            -e DB_HOST=${{ secrets.RDS_HOST }} \
            -e DB_NAME=${{ secrets.RDS_DB_NAME }} \
            -e DB_USER=${{ secrets.RDS_USER }} \
            -e DB_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            -e S3_BUCKET=nextcloud9999 \
            -e S3_REGION=ap-northeast-2 \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            585685714619.dkr.ecr.ap-northeast-2.amazonaws.com/nextcloud-repo:latest

    # ✅ EC2 인스턴스 2에 배포
    - name: Deploy to EC2 Instance 2 (43.201.10.15)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 43.201.10.15
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 585685714619.dkr.ecr.ap-northeast-2.amazonaws.com
          docker pull 585685714619.dkr.ecr.ap-northeast-2.amazonaws.com/nextcloud-repo:latest
          docker stop nextcloud-app || true
          docker rm nextcloud-app || true
          docker run -d \
            --name nextcloud-app \
            -p 80:80 \
            -e DB_HOST=${{ secrets.RDS_HOST }} \
            -e DB_NAME=${{ secrets.RDS_DB_NAME }} \
            -e DB_USER=${{ secrets.RDS_USER }} \
            -e DB_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            -e S3_BUCKET=nextcloud9999 \
            -e S3_REGION=ap-northeast-2 \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            585685714619.dkr.ecr.ap-northeast-2.amazonaws.com/nextcloud-repo:latest

