name: Build and Deploy to EKS via ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  CLUSTER_NAME: nextcloud-eks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Terraform Init & Output
      working-directory: terraform
      run: |
        terraform init -upgrade
        terraform output -raw ecr_url > ../ecr_url.txt

    - name: Set ECR_URL
      run: |
        echo "ECR_URL=$(cat ecr_url.txt)" >> $GITHUB_ENV
        echo "ECR_REGISTRY=$(cat ecr_url.txt | cut -d '/' -f 1)" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build and Push Docker Image
      run: |
        docker build -t nextcloud-app ./docker
        docker tag nextcloud-app:latest $ECR_URL:latest
        docker push $ECR_URL:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yml

